language: r
cache: packages

warnings_are_errors: true

os:
  - linux
  - osx

r:
  - 3.4
  - 3.5
  - 3.6
  - 4.0
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov(type = "all")'

