language: r
cache: packages
sudo: false

warnings_are_errors: ture

os:
  -linux
  -osx

r:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 4.0
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov(type = "all")'

